### ISSUE TITLE
Won't share if code contains unicode U+1F60E 😎

### ISSUE THREAD

**Issue by JoeMerten** [StackedCrooked/coliru#3]
Put this example code into coliru editor:

    #include<iostream>
    int main() {
        std::cout << "Hey there 😎" << std::endl;
        return 0;
    }

It will build & run properly. But when click "share" button, the editor became empty.

**Comment by StackedCrooked** [comment]
Fixed a while ago. See: https://github.com/StackedCrooked/coliru/commit/598828995aab086f06f7b47cd545d3b5424b77e4
