### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by JohannesMP** [StackedCrooked/coliru#6]
I recently switched some of my sites that I host statically on github pages over to cloudflare which can provide free https wrapper.

I noticed that when attempting to use the `http://coliru.stacked-crooked.com/compile` API on my multi-file frontend (#5), I now get a `Mixed Content` error, stating that 

> The page at 'https://compile.johannesmp.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://coliru.stacked-crooked.com/compile'. This request has been blocked; the content must be served over HTTPS.

Since I don't handle any sensitive information I _could_ disable cloudflare's wrapper, but with the industry [rapidly moving towards HTTPS](https://www.theregister.co.uk/2018/02/08/google_chrome_http_shame/), It would be nice if coliru (or at least its API) could be offered over HTTPS as well, if only for the sake of SEO.

**Comment by StackedCrooked** [comment]
HTTPS is now supported.
